In [1]:
import numpy as np
a = [1,2,3,4]
arr = np.array(a)

print(type(a))
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>


In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Two dimensional Array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr.shape)
print(arr.dtype)

(3, 3)
int64


In [5]:
#creating numpy arrays
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Syntax np.random.randint(start,end-1,size=(rows,column))
arr = np.random.randint(1,10,size=(3,3))
print(arr)

# Syntax : np.random(row,column)
arr = np.random.rand(2,2)
print(arr)

[[8 4 1]
 [2 4 7]
 [5 1 4]]
[[0.86324867 0.70759758]
 [0.76762878 0.34054058]]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(f"Mean of array is : {arr.mean()}")
print(type(arr))

[1 2 3 4 5]
Mean of array is : 3.0
<class 'numpy.ndarray'>


In [ ]:
# matrx Addition
arr = np.array([
                [1,2],
                [3,4]
                ])
arr2 = np.array([
                [2,3]
                ,[4,5]
                ])

arr3 = np.dot(arr,arr2)
print(arr3)

[[10 13]
 [22 29]]


In [17]:
# rank of matrix
arr = np.array([[1,2,3],
                [2,4,6],
                [1,1,1]])

rank = np.linalg.matrix_rank(arr)
print(f"Rank of matrix is : {rank}")

Rank of matrix is : 2


In [18]:
#Flatten result
print(f"Flatten is : {arr.flatten()}")

Flatten is : [1 2 3 2 4 6 1 1 1]


In [21]:
# result(Addition,substractio,multipliacaion,division),shape,dimension , flatten
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#Additionis 
result = arr + arr2
print(f"Result is : {result}")
print(f"Shape is : {result.shape}")
print(f"Dimension is : {result.ndim}")
print(f"Datatye is : {result.dtype}")
print(f"Rank is {np.linalg.matrix_rank(result)}")
print(f"flatten is : {arr.flatten()}")

Result is : [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Shape is : (3, 3)
Dimension is : 2
Datatye is : int64
Rank is 2
flatten is : [1 2 3 4 5 6 7 8 9]


In [24]:
#Substraction is 
result = arr - arr2
print(f"Result is : {result}")
print(f"Shape is : {result.shape}")
print(f"Dimension is : {result.ndim}")
print(f"Datatye is : {result.dtype}")
print(f"Rank is {np.linalg.matrix_rank(result)}")
print(f"flatten is : {arr.flatten()}")

Result is : [[0 0 0]
 [0 0 0]
 [0 0 0]]
Shape is : (3, 3)
Dimension is : 2
Datatye is : int64
Rank is 0
flatten is : [1 2 3 4 5 6 7 8 9]


In [22]:
# Multipliacation is 
result = np.dot(arr,arr2)
print(f"Result is : {result}")
print(f"Shape is : {result.shape}")
print(f"Dimension is : {result.ndim}")
print(f"Datatye is : {result.dtype}")
print(f"Rank is {np.linalg.matrix_rank(result)}")
print(f"flatten is : {arr.flatten()}")

Result is : [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Shape is : (3, 3)
Dimension is : 2
Datatye is : int64
Rank is 2
flatten is : [1 2 3 4 5 6 7 8 9]


In [25]:
#DIvision is 
result = arr //arr2
print(f"Result is : {result}")
print(f"Shape is : {result.shape}")
print(f"Dimension is : {result.ndim}")
print(f"Datatye is : {result.dtype}")
print(f"Rank is {np.linalg.matrix_rank(result)}")
print(f"flatten is : {arr.flatten()}")

Result is : [[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape is : (3, 3)
Dimension is : 2
Datatye is : int64
Rank is 1
flatten is : [1 2 3 4 5 6 7 8 9]
